# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmG6fUrmK9pq7N0M35RIlKqEg9lSQAGK
"""

def emoji_to_text(text):
  # Dictionary mapping emojis to text
  emoji_dict = {
        "😊": "happy",
        "😢": "sad",
        "❤️": "love",
        "🍕": "pizza",
        "😺": "cat",
        }

  return emoji_dict.get(text, text)